name: Dev

on:
  push:
    branches: [ develop ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.6
        env:
          MYSQL_ROOT_PASSWORD: "changeme123"
          MYSQL_DATABASE: "standard_notes_db"
          MYSQL_USER: "std_notes_user"
          MYSQL_PASSWORD: "changeme123"
        ports:
        - 3306:3306

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6.5
    - name: Copy default configuration
      run: cp .env.sample .env
    - name: Install dependencies
      run: bundle install
    - name: Setup database
      run: bundle exec rails db:create db:migrate
    - name: Run tests
      run: bundle exec rspec

  publish:
    needs: test

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Docker buildx
      id: buildx
      uses: crazy-max/ghaction-docker-buildx@v1
      with:
        version: latest
    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    - name: Publish to Registry
      run: |
        docker buildx build --push \
          --tag standardnotes/syncing-server:dev \
          --tag standardnotes/syncing-server:${{ github.sha }} \
          --platform linux/amd64,linux/arm64 .

  notify_slack:
    needs: [ publish ]

    runs-on: ubuntu-latest

    steps:
    - name: Notify slack
      uses: pullreminders/slack-action@master
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      with:
        args: '{ \"channel\": \"${{ secrets.SLACK_NOTIFICATION_CHANNEL }}\", \"blocks\": [{\"type\": \"section\", \"text\": {\"type\": \"mrkdwn\", \"text\": \"Successfully published <https://syncing-server-dev.standardnotes.org|[DEV] Syncing Server>\"}}, {\"type\": \"section\", \"text\": {\"type\": \"mrkdwn\", \"text\": \"Changes: <https://github.com/standardnotes/syncing-server/commit/${{ github.sha }}|${{ github.sha }}>\"}, \"accessory\": {\"type\": \"image\", \"image_url\": \"https://website-dev.standardnotes.org/assets/icon.png\", \"alt_text\": \"Standard Notes\"}}, { \"type\": \"section\", \"fields\": [{\"type\": \"mrkdwn\", \"text\": \"<https://github.com/standardnotes/syncing-server/actions/runs/${{ github.run_id }}|Build details>\"}]}]}'
